from models import Assignment

class AssignmentService:
    def __init__(self, db):
        self.db = db

    def post_job(self, student_id, title, description):
        # Create a new row in the 'assignments' table
        new_assignment = Assignment(
            student_id=student_id,
            title=title,
            description=description,
            status='open'
        )
        self.db.add(new_assignment)
        self.db.commit()
        # Refresh to get the ID generated by the database
        self.db.refresh(new_assignment) 
        return new_assignment
